<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<AssemblyName>Genshin FPS Unlock</AssemblyName>
		<RootNamespace>unlockfps_nc</RootNamespace>
		<StartupObject>unlockfps_nc.Program</StartupObject>
		<ApplicationManifest>Properties\app.manifest</ApplicationManifest>
		<ApplicationIcon>Resources\icon.ico</ApplicationIcon>
		<ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
		<ForceDesignerDpiUnaware>true</ForceDesignerDpiUnaware>

		<Company>Sefinek</Company>
		<Product>Genshin Impact FPS Unlock</Product>
		<Title>Genshin FPS Unlock</Title>
		<FileDescription>Safe tool that allows you to unlock the 60 FPS limit in Genshin Impact.</FileDescription>
		<Copyright>© 2021–Present 34736384, 2022–2026 Sefinek. Licensed under MIT</Copyright>
		<Authors>Sefinek;34736384</Authors>
		<NeutralLanguage>en-US</NeutralLanguage>

		<Version>4.3.1.0</Version>
		<AssemblyVersion>$(Version)</AssemblyVersion>
		<FileVersion>$(Version)</FileVersion>

		<PlatformTarget>x64</PlatformTarget>
		<SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
		<Prefer32Bit>false</Prefer32Bit>

		<SignAssembly>true</SignAssembly>
		<AssemblyOriginatorKeyFile>D:\Projects\stella\SignAssembly\FPS-Unlock.snk</AssemblyOriginatorKeyFile>

		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>

		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<IsPublishable>false</IsPublishable>
		<DebugType>portable</DebugType>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DebugType>embedded</DebugType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
		<PackageReference Include="NLog" Version="6.2.0" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Resources\UnlockerStub.dll" />
	</ItemGroup>

	<ItemGroup>
		<None Include="../LICENSE" Link="LICENSE">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Include="../README.md" Link="README.md">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Include="Genshin Stella Mod - The best and safest mod for Genshin Impact.url">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="NLog.config">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="unlocker.config.example.json">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Properties\ImageResources.Designer.cs">
			<AutoGen>True</AutoGen>
			<DesignTime>True</DesignTime>
			<DependentUpon>ImageResources.resx</DependentUpon>
		</Compile>
		<Compile Update="Properties\Resources.Designer.cs">
			<AutoGen>True</AutoGen>
			<DesignTime>True</DesignTime>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Properties\ImageResources.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>ImageResources.Designer.cs</LastGenOutput>
			<SubType>Designer</SubType>
		</EmbeddedResource>
		<EmbeddedResource Update="Properties\Resources.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
			<SubType>Designer</SubType>
		</EmbeddedResource>
	</ItemGroup>
</Project>
